// Compresses research/results-iteration1.json into lib/onethird-data.ts —
// the compact, checked-in dataset the /p/one-third-two-thirds instruments
// render. Rerun after extending the exhaustive range.
//
// Run: bun run research/emit-data.ts

interface LevelResult {
  n: number;
  posets: number;
  nonChain: number;
  minNum: string;
  minDen: string;
  atExactThird: number;
  below: number;
  runnerUp: { num: string; den: string; value: number } | null;
  extremal: Array<{ desc: string; num: string; den: string; pair: [number, number] }>;
  spectrum: Array<{ value: number; count: number }>;
}

const raw = await Bun.file(new URL("./results-iteration1.json", import.meta.url).pathname).json();
const results: LevelResult[] = raw.results;

const BINS = 37; // 1/3 .. 1/2 inclusive-ish, width (1/2 − 1/3)/36
const lo = 1 / 3;
const hi = 0.5;

const levels = results.map((r) => {
  const bins = new Array(BINS).fill(0);
  for (const s of r.spectrum) {
    const idx = Math.min(BINS - 1, Math.max(0, Math.floor(((s.value - lo) / (hi - lo)) * (BINS - 1) + 1e-9)));
    bins[idx] += s.count;
  }
  return {
    n: r.n,
    posets: r.posets,
    nonChain: r.nonChain,
    min: `${r.minNum}/${r.minDen}`,
    atExactThird: r.atExactThird,
    below: r.below,
    runnerUp: r.runnerUp ? { frac: `${r.runnerUp.num}/${r.runnerUp.den}`, value: r.runnerUp.value } : null,
    extremal: r.extremal.map((e) => e.desc),
    bins,
  };
});

const out = `// GENERATED by research/emit-data.ts from research/results-iteration1.json —
// do not edit by hand; rerun the pipeline instead:
//   bun run research/iteration1.ts && bun run research/emit-data.ts
// Exhaustive 1/3–2/3 verification data, exact at compute time; the "bins"
// histogram covers balance values in [1/3, 1/2] (${BINS} bins) for display.

export interface OneThirdLevel {
  n: number;
  posets: number;
  nonChain: number;
  min: string;
  atExactThird: number;
  below: number;
  runnerUp: { frac: string; value: number } | null;
  extremal: string[];
  bins: number[];
}

export const ONETHIRD_BINS = ${BINS};
export const ONETHIRD_RANGE: [number, number] = [1 / 3, 1 / 2];

export const ONETHIRD_LEVELS: OneThirdLevel[] = ${JSON.stringify(levels, null, 2)};
`;

await Bun.write(new URL("../lib/onethird-data.ts", import.meta.url).pathname, out);
console.log(`wrote lib/onethird-data.ts (n up to ${levels[levels.length - 1].n})`);
